# Generated by Django 5.1 on 2024-08-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bayer',
            new_name='Buyer',
        ),
    ]
