# Generated by Django 5.1 on 2024-09-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagination', '0002_post_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='choices',
        ),
    ]
